Fix command history rendering for long input and update UG for command history details
AY2324S2-CS2103T-F10-4/tp pull request #170
Opened 2024-04-10 13:01 UTC by YowSiaoKang

2024-04-11 08:55 UTC, SimKianSeng requested changes
Minor spelling errors. Otherwise ready to merge 👍🏻 .

2024-04-11 08:55 UTC, SimKianSeng commented on docs/UserGuide.md
> +- When the `perons.csv` or `assignments.csv` files are being used by another application running `export` command will result in an error.
seems like there is a typo here, should be `persons.csv`

2024-04-12 05:08 UTC, YowSiaoKang commented on docs/UserGuide.md
> +- When the `perons.csv` or `assignments.csv` files are being used by another application running `export` command will result in an error.
Updated

2024-04-12 06:35 UTC, SimKianSeng approved these changes
LGTM 👍🏻

2024-04-12 06:44 UTC, xuwen-ho approved these changes
well done

2024-04-12 06:45 UTC, merged