Update DG
AY2324S2-CS2103T-F10-4/tp pull request #175
Opened 2024-04-12 13:08 UTC by Benson15912

Updated our DG to fit requirements:
https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg

Added:
- Acknowledgement of my code reuse.
- Implementation of certain features: Add Volunteer feature, Find Volunteer Feature, Assign volunteer feature
- Removed proposed features: undo/redo
- Added use cases
- Added instructions for manual testing
- Added  Appendix: Effort

However, planned enhancements are left empty as of now.

2024-04-13 08:20 UTC, SimKianSeng reviewed
Minor comment, otherwise LGTM 👍🏻

2024-04-13 08:20 UTC, SimKianSeng commented on docs/images/AssignActivityDiagram.png
This one is it possible to have a single red box `Shows error message`?

2024-04-13 08:21 UTC, SimKianSeng approved these changes

2024-04-13 11:39 UTC, YowSiaoKang commented on docs/DeveloperGuide.md
> +- 2a. User enters an invalid volunteer.
I think the updated version will process invalid volunteer after confirmation. Will need to update.

2024-04-13 12:14 UTC, YowSiaoKang requested changes
Just need to clarify some points

2024-04-13 12:14 UTC, YowSiaoKang commented on docs/DeveloperGuide.md
> +3. Exit Application
should we use the `exit` CLI command instead of the GUI

2024-04-13 12:14 UTC, YowSiaoKang commented on docs/DeveloperGuide.md
> +   2. Test Case: `lista [extra inputs`
missing close bracket for `[extra inputs]`

2024-04-13 12:28 UTC, Benson15912 commented on docs/DeveloperGuide.md
> +3. Exit Application
Yup changed ut

2024-04-13 12:29 UTC, Benson15912 commented on docs/images/AssignActivityDiagram.png
I tried using the labels in the puml docs, but the diagram was very buggy

2024-04-14 08:50 UTC, YowSiaoKang commented on docs/DeveloperGuide.md
> +    - 5a1. Match shows an error message
The number is wrong

2024-04-14 11:47 UTC, Benson15912 commented on docs/DeveloperGuide.md
> +    - 5a1. Match shows an error message
Changed to 4

2024-04-14 14:05 UTC, YowSiaoKang approved these changes

2024-04-14 14:05 UTC, merged