Add Assignment Feature
AY2324S2-CS2103T-F10-4/tp pull request #63
Opened 2024-03-28 09:06 UTC by Benson15912

Fix #47
Fix #48 

I have added the feature to view assignments by "lista" command and added the feature to assign people by:

assign [index] [assignment details] [date]

Extra features needed and will be implemented in separate PRs:

- Check if assigned person is available on that date
- Duplicate assignments
- Assign multiple volunteers
- Removing an assignment
- Filtering Assignments

2024-03-28 16:47 UTC, SimKianSeng requested changes
# Overall comments
Feature seems useful 👍🏻. Perhaps we need to take note to not morph our application too much into a scheduling application. Perhaps @xuwen-ho, @tayziyi, @YowSiaoKang can comment?

# Refinements
* Possible to have another panel side by side to show the volunteers, hard to remember the name and assignments?
* Perhaps we can not have duplicate assignment names?
* Perhaps we can assign multiple volunteers to the same assignment?
* Perhaps the font color for the header can be improved? It might be hard to see the black header in the dark background.
* Minor issues on text alignment with the header.

2024-03-29 02:30 UTC, tayziyi reviewed
Overall, good OOP practices shown and no serious code quality issues.

2024-03-29 02:30 UTC, tayziyi commented on src/main/java/seedu/address/logic/Messages.java
> +    public static String format(Assignment assignment) {
Good use of overloading

2024-03-29 02:30 UTC, tayziyi commented on src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds an assignment to the address book. "
Consider adding more line breaks ("\n") as the line gets too long.

2024-03-29 02:30 UTC, tayziyi commented on src/main/java/seedu/address/model/assignment/Assignment.java
> +    public Assignment(Person assignedPerson, AssignmentDetails details, Availability availability) {
Validation would be good here "requireAllNonNull" to ensure parameters are not null

2024-03-29 02:30 UTC, tayziyi commented on src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
> +    public AddAssignmentCommand(Index index, AssignmentDetails details, Availability availability) {
Good practice to be consistent in naming - AssignmentDetails assignmentDetails

2024-03-29 02:47 UTC, tayziyi requested changes
# Overall comments
Overall, feature is a good to have. Agree that we do have to be caution not to shift our focus from our original volunteer database.

# Suggested Improvements
* Should it be possible to assign volunteers to an assignment where it is not stated in their availability.
* Perhaps change "lista" to "view" command word as it is clearer.
* Perhaps change colour scheme when we are viewing assignments. Black words on dark colour scheme.
* Perhaps show assignment details in original volunteer list, to show which assignment they are working on.
* Perhaps add duration to the assignment (maybe the assignment spans over 3 days or it is just an ad-hoc assignment for 1 day)

2024-03-29 09:44 UTC, YowSiaoKang commented on src/main/java/seedu/address/ui/MainWindow.java
> +            return;
Good defensive coding here even though this case will most likely not be reached.

2024-03-29 09:44 UTC, YowSiaoKang commented on src/main/java/seedu/address/model/assignment/Assignment.java
> +
Instead of `Assignment` maybe it can be named `Activity` or `Event` as it can be misunderstood as an association class.

2024-03-29 15:01 UTC, Benson15912 commented on src/main/java/seedu/address/model/assignment/Assignment.java
> +    public Assignment(Person assignedPerson, AssignmentDetails details, Availability availability) {
Noted, have added this.

2024-03-30 14:26 UTC, xuwen-ho approved these changes
lgtm

2024-03-30 14:27 UTC, merged